[package]
name = "pidcat"
edition = "2024"
version = "1.2.1"
build = "build/build.rs"
description = "A colorized Android logcat viewer with advanced filtering capabilities."
authors = ["AbdElMoniem ElHifnawy <hifnawy_moniem@hotmail.com>"]

[workspace]
members = [
  ".",
  "build/xshell",
  "build/xtask",
]

[dependencies]
ctrlc = "3.5.2"
regex = "1.12.3"
colored = "3.1.1"
itertools = "0.14.0"
lazy_static = "1.5.0"
is-terminal = "0.4.17"
terminal_size = "0.4.3"
clap_complete = "4.5.66"
scope-functions = "1.1.0"
strip-ansi-escapes = "0.2.1"
clap = { version = "4.5.60", features = ["derive"] }

[build-dependencies]
build-print = "1.0.1"
embed-resource = "3.0.6"
scope-functions = "1.1.0"

[[bin]]
name = "pidcat"
path = "src/bin/main.rs"

[dev-dependencies]
build-print = "1.0.1"

[profile.release]
debug = true
strip = false
