[package]
name = "pidcat"
edition = "2024"
version = "1.2.1"
build = "build/build.rs"
description = "A colorized Android logcat viewer with advanced filtering capabilities."
authors = ["AbdElMoniem ElHifnawy <hifnawy_moniem@hotmail.com>"]

[workspace]
members = [
  ".",
  "build/xshell",
  "build/xtask",
]

[dependencies]
ctrlc = "3.5.2"
regex = "1.12.3"
colored = "3.1.1"
arboard = "3.6.1"
ratatui = "0.30.2"
crossterm = "0.29"
itertools = "0.14.0"
lazy_static = "1.5.0"
is-terminal = "0.4.17"
terminal_size = "0.4.3"
clap_complete = "4.5.66"
scope-functions = "1.1.0"
strip-ansi-escapes = "0.2.1"
clap = { version = "4.5.60", features = ["derive"] }
tui-file-explorer = { version = "2.3.0", default-features = false }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "io-util", "io-std", "fs", "process", "sync", "macros", "time"] }
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
etcetera = "0.11.0"
serde = { version = "1.0.229", features = ["derive"] }
toml = { version = "1.1.6", features = ["preserve_order"] }

[build-dependencies]
build-print = "1.0.1"
embed-resource = "3.0.6"
scope-functions = "1.1.0"

[[bin]]
name = "pidcat"
path = "src/bin/main.rs"

[dev-dependencies]
build-print = "1.0.1"

[profile.release]
debug = true
strip = false
