# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish Release On Tag
run-name: ${{ github.workflow }} ${{ github.ref_name }} ${{ github.event.repository.updated_at}}

on:
  push:
    tags:
      - "v[0-9]+"
      - "v[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build And Test
    uses: ./.github/workflows/build_installer.yml
    secrets: inherit

  publish-release-on-tag:
    name: Publish Release On Tag
    needs: [build-and-test]
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Git Cliff Body Template
        id: git-cliff-body-template
        run: |
          $content = cat -raw cliff_body_ci.tera

          "content<<EOF" >> $env:GITHUB_OUTPUT
          $content >> $env:GITHUB_OUTPUT
          "EOF" >> $env:GITHUB_OUTPUT

      - name: Generate Changelog
        id: generate-changelog
        uses: orhun/git-cliff-action@v4
        env:
          BODY_CONTENT: ${{ steps.git-cliff-body-template.outputs.content }}
        with:
          config: cliff.toml
          args: --latest --strip=all --body="$BODY_CONTENT"

      - name: Download Artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-and-test.outputs.artifact_name }}
          path: artifacts

      - name: Get Artifact Path
        id: get-artifact-path
        run: |
          $artifactPath = $(ls ${{ steps.download-artifact.outputs.download-path }}\*.exe -recurse).FullName

          echo "artifact_path=$artifactPath" >> $env:GITHUB_OUTPUT

      - name: Publish Release ${{ github.ref_name }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ steps.get-artifact-path.outputs.artifact_path }}
          tag: ${{ github.ref }}
          draft: false
          make_latest: true
          overwrite: true
          promote: true
          body: ${{ steps.generate-changelog.outputs.content }}
          release_name: ${{ github.ref_name }}
          repo_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}